apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bb-1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Increase memory limit to 1GiB to prevent OOM errors
        run.googleapis.com/memory: 1Gi
        # Set CPU to 1 for better performance
        run.googleapis.com/cpu: "1"
        # Enable CPU throttling only when idle
        run.googleapis.com/cpu-throttling: "true"
        # Set max instances to prevent runaway costs
        autoscaling.knative.dev/maxScale: "10"
        # Set min instances (0 for scale to zero, 1+ for warm starts)
        autoscaling.knative.dev/minScale: "0"
        # Request timeout
        run.googleapis.com/timeout: 300s
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/penify-prod/bb-1:latest
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            # Memory limit - increased from 512Mi to 1Gi
            memory: 1Gi
            # CPU limit
            cpu: "1"
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        # Startup probe to prevent premature traffic
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
